//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash_Multi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flash_Multi.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader upgrade app written successfully.
        ///
        ///The app will now update the bootloader on the MULTI-Module.
        ///
        ///DO NOT UNPLUG THE MULTI-MODULE UNTIL THE RED LED GOES OUT AND REMAINS OFF FOR 5 SECONDS!.
        /// </summary>
        internal static string bootloaderUpgradeDone {
            get {
                return ResourceManager.GetString("bootloaderUpgradeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the bootloader upgrade app!.
        /// </summary>
        internal static string bootloaderUpgradeFailed {
            get {
                return ResourceManager.GetString("bootloaderUpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading the bootloader will erase the MULTI-Module firmware.  New firmware will need to be written to the module before it is usable.
        ///
        ///The red LED on the MULTI-Module will indicate the progress of the bootloader upgrade.
        ///
        ///Once the bootloader upgrade is started the module must not be unplugged until the red LED remains off for 5s.
        ///
        ///Once the LED has been off for 5s, unplug the module, plug it back in, then write new firmware to it.
        ///
        ///Click OK to proceed..
        /// </summary>
        internal static string bootloaderUpgradePrompt {
            get {
                return ResourceManager.GetString("bootloaderUpgradePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting DFU Recovery Mode..
        /// </summary>
        internal static string dfuAttemptingRecovery {
            get {
                return ResourceManager.GetString("dfuAttemptingRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFU Recovery cancelled..
        /// </summary>
        internal static string dfuRecoveryCancelled {
            get {
                return ResourceManager.GetString("dfuRecoveryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFU Recovery failed..
        /// </summary>
        internal static string dfuRecoveryFailed {
            get {
                return ResourceManager.GetString("dfuRecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the MULTI-Module to DFU Mode?.
        /// </summary>
        internal static string dfuResetPrompt {
            get {
                return ResourceManager.GetString("dfuResetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader Upgrade.
        /// </summary>
        internal static string dialogTitleBootloaderUpgrade {
            get {
                return ResourceManager.GetString("dialogTitleBootloaderUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to DFU Mode.
        /// </summary>
        internal static string dialogTitleDfuReset {
            get {
                return ResourceManager.GetString("dialogTitleDfuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Driver Installation.
        /// </summary>
        internal static string dialogTitleDriverInstaller {
            get {
                return ResourceManager.GetString("dialogTitleDriverInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module Erase.
        /// </summary>
        internal static string dialogTitleErase {
            get {
                return ResourceManager.GetString("dialogTitleErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file to flash.
        /// </summary>
        internal static string dialogTitleFileOpen {
            get {
                return ResourceManager.GetString("dialogTitleFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module Read.
        /// </summary>
        internal static string dialogTitleRead {
            get {
                return ResourceManager.GetString("dialogTitleRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Multi Update Check.
        /// </summary>
        internal static string dialogTitleUpdateCheck {
            get {
                return ResourceManager.GetString("dialogTitleUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module Write.
        /// </summary>
        internal static string dialogTitleWrite {
            get {
                return ResourceManager.GetString("dialogTitleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the MULTI-Module USB drivers?
        ///
        ///If you are upgrading ore replacing existing drivers, ensure that the MULTI-Module is plugged in before proceeding..
        /// </summary>
        internal static string driverInstallerPrompt {
            get {
                return ResourceManager.GetString("driverInstallerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed!.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to erase the MULTI-Module!.
        /// </summary>
        internal static string failedtoEraseModule {
            get {
                return ResourceManager.GetString("failedtoEraseModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open port.
        /// </summary>
        internal static string failedToOpenPort {
            get {
                return ResourceManager.GetString("failedToOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the MULTI-Module!.
        /// </summary>
        internal static string failedToReadModule {
            get {
                return ResourceManager.GetString("failedToReadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the bootloader..
        /// </summary>
        internal static string failedToWriteBootloader {
            get {
                return ResourceManager.GetString("failedToWriteBootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the bootloader upgrader!.
        /// </summary>
        internal static string failedToWriteBootReloader {
            get {
                return ResourceManager.GetString("failedToWriteBootReloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write MULTI-Module EEPROM!.
        /// </summary>
        internal static string failedToWriteEeprom {
            get {
                return ResourceManager.GetString("failedToWriteEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write MULTI-Module firmware!.
        /// </summary>
        internal static string failedToWriteFirmware {
            get {
                return ResourceManager.GetString("failedToWriteFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading MULTI-Module Bootloader.
        /// </summary>
        internal static string modeBootloaderUpgrade {
            get {
                return ResourceManager.GetString("modeBootloaderUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string modeDfuSwitch {
            get {
                return ResourceManager.GetString("modeDfuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing MULTI-Module.
        /// </summary>
        internal static string modeErasing {
            get {
                return ResourceManager.GetString("modeErasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading MULTI-Module.
        /// </summary>
        internal static string modeReading {
            get {
                return ResourceManager.GetString("modeReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing MULTI-Module.
        /// </summary>
        internal static string modeWriting {
            get {
                return ResourceManager.GetString("modeWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing flash memory ....
        /// </summary>
        internal static string progressErasingFlash {
            get {
                return ResourceManager.GetString("progressErasingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing MULTI-Module DFU Bootloader Driver ....
        /// </summary>
        internal static string progressInstallingDfuDriver {
            get {
                return ResourceManager.GetString("progressInstallingDfuDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing MULTI-Module USB Serial Driver ....
        /// </summary>
        internal static string progressInstallingUsbSerialDriver {
            get {
                return ResourceManager.GetString("progressInstallingUsbSerialDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading flash memory ....
        /// </summary>
        internal static string progressReadingFlash {
            get {
                return ResourceManager.GetString("progressReadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching MULTI-Module into DFU mode ....
        /// </summary>
        internal static string progressSwitchingToDfuMode {
            get {
                return ResourceManager.GetString("progressSwitchingToDfuMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing bootloader ....
        /// </summary>
        internal static string progressWritingBootloader {
            get {
                return ResourceManager.GetString("progressWritingBootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing BootReloader to MULTI-Module ....
        /// </summary>
        internal static string progressWritingBootReloader {
            get {
                return ResourceManager.GetString("progressWritingBootReloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing firmware to MULTI-Module ....
        /// </summary>
        internal static string progressWritingFirmware {
            get {
                return ResourceManager.GetString("progressWritingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module erased successfully..
        /// </summary>
        internal static string succeededErasing {
            get {
                return ResourceManager.GetString("succeededErasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootReloader written successfully.
        ///
        ///DO NOT UNPLUG THE MULTI-MODULE UNTIL THE RED LED GOES OUT AND REMAINS OFF FOR 5 SECONDS!
        ///
        ///You will need to write new firmware to the MULTI-Module..
        /// </summary>
        internal static string succeededWritingBootReloader {
            get {
                return ResourceManager.GetString("succeededWritingBootReloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module EEPROM written successfully..
        /// </summary>
        internal static string succeededWritingEeprom {
            get {
                return ResourceManager.GetString("succeededWritingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI-Module firmware written successfully..
        /// </summary>
        internal static string succeededWritingFirmware {
            get {
                return ResourceManager.GetString("succeededWritingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed!.
        /// </summary>
        internal static string updateCheckFailed {
            get {
                return ResourceManager.GetString("updateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version of Flash Multi..
        /// </summary>
        internal static string updateNoUpdate {
            get {
                return ResourceManager.GetString("updateNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of Flash Multi is available.\n\nYou have Flash Multi.
        /// </summary>
        internal static string updatePromptPart1 {
            get {
                return ResourceManager.GetString("updatePromptPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and Flash Multi.
        /// </summary>
        internal static string updatePromptPart2 {
            get {
                return ResourceManager.GetString("updatePromptPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is available.\n\nSee the latest release on Github?.
        /// </summary>
        internal static string updatePromptPart3 {
            get {
                return ResourceManager.GetString("updatePromptPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via native USB.
        /// </summary>
        internal static string viaNativeUSB {
            get {
                return ResourceManager.GetString("viaNativeUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via serial.
        /// </summary>
        internal static string viaSerial {
            get {
                return ResourceManager.GetString("viaSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via USBasp.
        /// </summary>
        internal static string viaUSBasp {
            get {
                return ResourceManager.GetString("viaUSBasp", resourceCulture);
            }
        }
    }
}
